# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

setup_travis

desc 'Increments by 1 last build number'
def bump_build_number
  build_number = get_build_number(xcodeproj: "Caoculadora.xcodeproj")
  number = build_number.to_i + 1
  increment_build_number(
    build_number: number.to_s
  )
  # commit_version_bump(
  #   message: "Build Number Bump",
  #   xcodeproj: XCODEPROJ
  # )
end

desc "Push a new beta build to TestFlight"
lane :beta do
  match(
    type: "development",
    readonly: true
  )

  match(
    type: "adhoc",
    readonly: true
  ) 

  match(
    type: "appstore",
    readonly: true
  )

  bump_build_number
  ipa = build_app(
    scheme: "Caoculadora",
    output_directory: "./builds"
  )

  upload_to_testflight(
    ipa: ipa
  )
end